---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: 8.12-jessie

inputs:
  - name: dev-ed-for-bernie
  - name: ci

caches:
  - path: dev-ed-for-bernie/node_modules

run:
  path: ci/ed-for-bernie/tasks/deploy-dev/run.sh