---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: 8.12-jessie

inputs:
  - name: prod-worker-town-hall
  - name: ci

caches:
  - path: member-handbook/node_modules

run:
  path: ci/worker-town-hall/tasks/deploy-prod/run.sh