resources:
  - name: ci
    type: git
    source:
      uri: git@gitlab.com:Kropotcat/chicago-dsa-pipeline.git
      branch: master
      private_key: ((gitlab-gpg-key))

  - name: dev-ed-for-bernie
    type: git
    source:
      uri: git@gitlab.com:Kropotcat/Educators-For-Bernie.git
      branch: dev
      private_key: ((gitlab-gpg-key))

  - name: prod-ed-for-bernie
    type: git
    source:
      uri: git@gitlab.com:Kropotcat/Educators-For-Bernie.git
      branch: master
      private_key: ((gitlab-gpg-key))

jobs:
  - name: Unit-Tests
    plan:
      - aggregate:
          - get: dev-ed-for-bernie
            trigger: true
          - get: ci
            trigger: false
      - task: run-unit-tests
        file: ci/ed-for-bernie/tasks/unit-test/task.yml

  - name: Deploy to Dev VM
    plan:
      - aggregate:
          - get: dev-ed-for-bernie
            passed:
              - Unit-Tests
            trigger: true
          - get: ci
            trigger: false
      - task: deploy-to-vm
        file: ci/ed-for-bernie/tasks/deploy-dev/task.yml
        params:
          RSA_KEY: ((deploy-rsa-key))

  - name: Deploy to Prod VM
    plan:
      - aggregate:
          - get: prod-ed-for-bernie
            trigger: false
          - get: ci
            trigger: false
      - task: deploy-to-vm
        file: ci/ed-for-bernie/tasks/deploy-prod/task.yml
        params:
          RSA_KEY: ((deploy-rsa-key))


groups:
  - name: Development
    jobs:
      - Unit-Tests
      - Deploy to Dev VM
  - name: Production
    jobs:
      - Deploy to Prod VM